#!/bin/bash
# run-tests --- Run unit tests in mocha - passing commandline options.

set -e

cd $PROJ_DIR

if [[ "$1" == "--help" ]]; then
  echo "Usage: run-tests [--build] [--cover] [--grep pattern]"
  echo "  --build: Rebuild before running tests."
  echo "  --cover: Open code coverage in browser after running tests."
  echo "  --debug: Use Chrome Dev Tools to debug test."
  echo "  --grep <pattern>: Only run tests whose description matches pattern."
  exit 0
fi

if [[ ! -d "node_modules" ]]; then
  echo "Project not yet configured to run tests."
  echo "Run: configure-project command."
  exit 1
fi

MOCHA_ARGS="--ui tdd --require source-map-support/register lib/test"
EXTRA_MOCHA_ARGS=""

for flag in "$@"; do
  case "$flag" in
    --build)
      build=true;
      ;;
    --cover)
      cover=true
      ;;
    --debug)
      debug=true
      ;;
    *)
      EXTRA_MOCHA_ARGS="$EXTRA_MOCHA_ARGS $flag"
      ;;
  esac
done

if [[ $build ]]; then
  build-project
fi

echo -e "\nmocha $MOCHA_ARGS $EXTRA_MOCHA_ARGS ..."

# Use istanbul for code coverage, while using mocha as the test runner.
if [[ $debug ]]; then
  mocha --inspect --debug-brk $MOCHA_ARGS $EXTRA_MOCHA_ARGS
elif [[ $cover ]]; then
  istanbul cover --print detail _mocha -- $MOCHA_ARGS $EXTRA_MOCHA_ARGS
else
  mocha $MOCHA_ARGS $EXTRA_MOCHA_ARGS
fi

# Open lcov coverage report in the browser (this probably only works on Mac).
if [[ $cover ]]; then
  open coverage/lcov-report/lib/index.html
fi
