#!/bin/bash
# run-tests --- Run unit tests in mocha - passing commandline options.

set -e

cd $PROJ_DIR

if [[ "$1" == "--help" ]]; then
  echo "Usage: run-tests [--build] [--cover] [--grep pattern]"
  echo "  --build: Rebuild before running tests."
  echo "  --cover: Open code coverage in browser after running tests."
  echo "  --grep <pattern>: Only run tests whose description matches pattern."
  exit 0
fi

if [[ ! -d "node_modules" ]]; then
  echo "Project not yet configured to run tests."
  echo "Run: configure-project command."
  exit 1
fi

if [[ "$1" == "--build" ]]; then
  shift
  build-project
fi

if [[ "$1" == "--cover" ]]; then
  shift
  cover=true
fi

# Use istanbul for code coverage, while using mocha as the test runner.
istanbul cover --print detail \
         _mocha -- \
         --ui tdd \
         --require "source-map-support/register" \
         lib/test "$@"

# Open lcov coverage report in the browser (this probably only works on Mac).
if [[ cover ]]; then
  open coverage/lcov-report/lib/index.html
fi
